env:
  browser: true
parserOptions:
  ecmaVersion: 2015
  sourceType: module
  project: ./tsconfig.json
parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - airbnb
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - "node_modules"
  - "dist"
  - "vite.config.ts"
rules:
  react/function-component-definition: off
  react/react-in-jsx-scope: off
