parser: "@typescript-eslint/parser"
plugins:
  - "svelte3"
  - "@typescript-eslint"
overrides:
  - processor: "svelte3/svelte3"
    files:
      - "*.svelte"
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
rules:
  "import/no-extraneous-dependencies": "off"
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
  "import/prefer-default-export": "off"
  "import/no-mutable-exports": "off"
settings:
  "svelte3/typescript": true
env:
  browser: true
